version: "3.7"

services:
  webglivesdb:
    image: postgres:12-bullseye
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: "webglivesdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pwd"

  seq:
    image: datalust/seq:latest
    ports: 
      - 5341:80
    environment:
      ACCEPT_EULA: Y
